spin_manifest_version = 2

[application]
authors = ["karthik2804 <karthik.ganeshram@fermyon.com>"]
description = ""
name = "s3"
version = "0.1.0"

[[trigger.http]]
route = "/..."
component = "s3"

[component.s3]
source = "dist/s3.wasm"
exclude_files = ["**/node_modules"]
allowed_outbound_hosts = ["https://*.s3.us-west-2.amazonaws.com"]
[component.s3.build]
command = ["npm install", "npm run build"]
watch = ["src/**/*.ts"]
