spin_manifest_version = 2

[application]
authors = ["karthik2804 <karthik.ganeshram@fermyon.com>"]
description = ""
name = "spin-sqlite"
version = "0.1.0"

[[trigger.http]]
route = "/..."
component = "spin-sqlite"

[component.spin-sqlite]
source = "dist/spin-sqlite.wasm"
exclude_files = ["**/node_modules"]
sqlite_databases = ["default"]
[component.spin-sqlite.build]
command = ["npm install", "npm run build"]
watch = ["src/**/*.ts"]
