spin_manifest_version = 2

[application]
authors = ["karthik2804 <karthik.ganeshram@fermyon.com>"]
description = ""
name = "spin-llm"
version = "0.1.0"

[[trigger.http]]
route = "/..."
component = "spin-llm"

[component.spin-llm]
source = "dist/spin-llm.wasm"
exclude_files = ["**/node_modules"]
allowed_models = ["llama2-chat"]
[component.spin-llm.build]
command = ["npm install", "npm run build"]
watch = ["src/**/*.ts"]
