manifest_version = "1"
id = "http-js"
description = "HTTP request handler using JavaScript"

[add_component]
skip_files = ["spin.toml"]
[add_component.snippets]
component = "component.txt"

[parameters]
project-description = { type = "string", prompt = "Description", default = "" }
http-path = { type = "string", prompt = "HTTP path", default = "/...", pattern = "^/\\S*$" }
http-router = { type = "string", prompt = "HTTP Router", default = "itty", allowed_values = [
    "itty",
    "hono",
    "none",
] }
