spin_manifest_version = 2

[application]
name = "{{project-name | kebab_case}}"
version = "0.1.0"
authors = ["{{authors}}"]
description = "{{project-description}}"

[application.trigger.redis]
address = "{{redis-address}}"

[[trigger.redis]]
channel = "{{redis-channel}}"
component = "{{project-name | kebab_case}}"

[component.{{project-name | kebab_case}}]
source = "dist/{{project-name | kebab_case}}.wasm"
exclude_files = ["**/node_modules"]
allowed_outbound_hosts = []

[component.{{project-name | kebab_case}}.build]
command = ["{{package-manager}} install", "{{package-manager}} run build"]
watch = ["src/**/*.ts", "package.json"]
