spin_manifest_version = 2

[application]
authors = ["karthik2804 <karthik.ganeshram@fermyon.com>"]
description = ""
name = "spin-postgres"
version = "0.1.0"

[[trigger.http]]
route = "/..."
component = "spin-postgres"

[component.spin-postgres]
source = "dist/spin-postgres.wasm"
exclude_files = ["**/node_modules"]
allowed_outbound_hosts = ["postgres://localhost"]
[component.spin-postgres.build]
command = ["npm install", "npm run build"]
watch = ["src/**/*.ts"]
