[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace]
members = ["crates/wit-tools"]
resolver = "2"

[workspace.dependencies]
anyhow = "1.0.86"
wit-bindgen = "0.27.0"
wit-bindgen-core = "0.27.0"
wit-component = "0.219.1"
wit-parser = "0.219.1"
