// DO NOT EDIT THIS FILE
// It is used by spin to generate a http component
import { SimpleHTTP } from "@fermyon/spin-sdk";
import { handleRequest } from ".";

class HttpHandler extends SimpleHTTP {
    constructor() {
        super();
    }
    handleRequest = handleRequest
}

export const incomingHandler = new HttpHandler()