spin_manifest_version = 2

[application]
authors = ["karthik2804 <karthik.ganeshram@fermyon.com>"]
description = ""
name = "outbound-http"
version = "0.1.0"

[[trigger.http]]
route = "/..."
component = "outbound-http"

[component.outbound-http]
source = "dist/outbound-http.wasm"
exclude_files = ["**/node_modules"]
allowed_outbound_hosts = ["https://random-data-api.fermyon.app/"]
[component.outbound-http.build]
command = ["npm install", "npm run build"]
watch = ["src/**/*.ts"]
