spin_manifest_version = 2

[application]
authors = ["karthik2804 <karthik.ganeshram@fermyon.com>"]
description = ""
name = "qstash"
version = "0.1.0"

[[trigger.http]]
route = "/..."
component = "qstash"

[component.qstash]
source = "target/qstash.wasm"
exclude_files = ["**/node_modules"]
allowed_outbound_hosts = ["https://qstash.upstash.io:443"]
[component.qstash.build]
command = "npm run build"
watch = ["src/**/*.ts", "package.json"]
