spin_manifest_version = 2

[application]
authors = ["karthik2804 <karthik.ganeshram@fermyon.com>"]
description = ""
name = "backblaze"
version = "0.1.0"

[[trigger.http]]
route = "/..."
component = "backblaze"

[component.backblaze]
source = "dist/backblaze.wasm"
exclude_files = ["**/node_modules"]
allowed_outbound_hosts = ["https://*.backblazeb2.com"]
[component.backblaze.build]
command = ["npm install", "npm run build"]
watch = ["src/**/*.ts"]
