spin_manifest_version = 2

[application]
authors = ["karthik2804 <karthik.ganeshram@fermyon.com>"]
description = ""
name = "sqs"
version = "0.1.0"

[[trigger.http]]
route = "/..."
component = "sqs"

[component.sqs]
source = "dist/sqs.wasm"
exclude_files = ["**/node_modules"]
allowed_outbound_hosts = ["https://*.amazonaws.com"]
[component.sqs.build]
command = ["npm install", "npm run build"]
watch = ["src/**/*.ts"]
