spin_manifest_version = 2

[application]
authors = ["karthik2804 <karthik.ganeshram@fermyon.com>"]
description = ""
name = "spin-redis"
version = "0.1.0"

[[trigger.http]]
route = "/..."
component = "spin-redis"

[component.spin-redis]
source = "dist/spin-redis.wasm"
exclude_files = ["**/node_modules"]
allowed_outbound_hosts = ["redis://localhost:6379"]
[component.spin-redis.build]
command = ["npm install", "npm run build"]
watch = ["src/**/*.ts"]
