CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY, name TEXT NOT NULL, age INTEGER);
INSERT OR REPLACE INTO users (id, name, age) VALUES (1, 'Dan', 30);
INSERT OR REPLACE INTO users (id, name, age) VALUES (2, 'Alice', 25);