manifest_version = "1"
id = "http-ts"
description = "HTTP request handler using TypeScript"

[add_component]
skip_files = ["spin.toml"]
[add_component.snippets]
component = "component.txt"

[parameters]
project-description = { type = "string", prompt = "Description", default = "" }
http-path = { type = "string", prompt = "HTTP path", default = "/...", pattern = "^/\\S*$" }
enable-aot = { type = "string", prompt = "enable AoT Compilation [y/N]", default = "Y", pattern = "^[yYnN]$" }
