spin_manifest_version = 2

[application]
authors = ["karthik2804 <karthik.ganeshram@fermyon.com>"]
description = ""
name = "spin-kv"
version = "0.1.0"

[[trigger.http]]
route = "/..."
component = "spin-kv"

[component.spin-kv]
source = "dist/spin-kv.wasm"
exclude_files = ["**/node_modules"]
key_value_stores = ["default"]
[component.spin-kv.build]
command = ["npm install", "npm run build"]
watch = ["src/**/*.ts"]
