spin_manifest_version = 2

[application]
authors = ["karthik2804 <karthik.ganeshram@fermyon.com>"]
description = ""
name = "drizzle"
version = "0.1.0"

[[trigger.http]]
route = "/..."
component = "drizzle"

[component.drizzle]
source = "target/drizzle.wasm"
exclude_files = ["**/node_modules"]
sqlite_databases = ["default"]
[component.drizzle.build]
command = "npm run build"
watch = ["src/**/*.ts", "package.json"]
