spin_manifest_version = 2

[application]
authors = ["karthik2804 <karthik.ganeshram@fermyon.com>"]
description = ""
name = "neondb"
version = "0.1.0"

[[trigger.http]]
route = "/..."
component = "neondb"

[component.neondb]
source = "dist/neondb.wasm"
exclude_files = ["**/node_modules"]
allowed_outbound_hosts = ["https://*.aws.neon.tech"]
[component.neondb.build]
command = ["npm install", "npm run build"]
watch = ["src/**/*.ts"]
