spin_manifest_version = 2

[application]
authors = ["karthik2804 <karthik.ganeshram@fermyon.com>"]
description = ""
name = "planetscale"
version = "0.1.0"

[[trigger.http]]
route = "/..."
component = "planetscale"

[component.planetscale]
source = "dist/planetscale.wasm"
exclude_files = ["**/node_modules"]
allowed_outbound_hosts = ["https://aws.connect.psdb.cloud"]
[component.planetscale.build]
command = ["npm install", "npm run build"]
watch = ["src/**/*.ts"]
