manifest_version = "1"
id = "redis-ts"
description = "Redis message handler using TypeScript"
tags = ["redis", "ts"]

[add_component]
skip_files = ["spin.toml"]
[add_component.snippets]
component = "component.txt"
application_trigger = "application-trigger.txt"
[add_component.conditions.address_exists]
condition = { manifest_entry_exists = "application.trigger.redis" }
skip_parameters = ["redis-address"]
skip_snippets = ["application_trigger"]

[parameters]
project-description = { type = "string", prompt = "Description", default = "" }
redis-address = { type = "string", prompt = "Redis address", default = "redis://localhost:6379" }
redis-channel = { type = "string", prompt = "Redis channel" }
package-manager = { type = "string", prompt = "Which package manager would you like to use (npm|yarn)", default = "npm", pattern = "^(npm|yarn)$" }
