name: Test Templates

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  test_http_template:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        router: ['hono', 'itty', 'none']

    steps:
      - uses: actions/checkout@v7

      - name: Use Node.js 22
        uses: actions/setup-node@v7
        with:
          node-version: 22

      - name: Setup `spin`
        uses: fermyon/actions/spin/setup@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install templates
        run: spin templates install --dir .

      - name: Create new project
        run: spin new -t http-ts --value http-router=${{ matrix.router }} -a test-project

      - name: Add new component to project
        run: |
          cd test-project
          spin add -t http-ts --value http-router=${{ matrix.router }} -a new-component
          cd new-component
          npm install

      - name: Build the application
        run: |
          cd test-project
          spin build

  test_redis_template:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        template: [redis-js, redis-ts]

    steps:
      - uses: actions/checkout@v7

      - name: Use Node.js 22
        uses: actions/setup-node@v7
        with:
          node-version: 22

      - name: Setup `spin`
        uses: fermyon/actions/spin/setup@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install templates
        run: spin templates install --dir .

      - name: Create new project
        run: spin new -t ${{ matrix.template }} -a test-project

      - name: Add new component to project
        run: |
          cd test-project
          spin add -t ${{ matrix.template }} -a new-component
          cd new-component
          npm install

      - name: Build the application
        run: |
          cd test-project
          spin build
